version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      drizzle:
        patterns:
          - drizzle-orm
          - drizzle-kit
          - drizzle-zod
    ignore:
      - dependency-name: "drizzle-orm"
        versions: ["beta", "rc"]
      - dependency-name: "drizzle-kit"
        versions: ["beta", "rc"]
    open-pull-requests-limit: 5
